Repository Aupet-Group/aupet-app, pull requests merged in 2019-09, with the labels that each got.

#59 PR Add event #30
  app.js
  model/event.js
  routes/auth.js
  routes/events.js
  routes/users.js
  views/events/events.hbs
  views/events/newevent.hbs
Labels: story

#96 Redo homepage #75
  package-lock.json
  public/images/facebook.svg
  public/images/hmenu.png
  public/images/instagram.svg
  public/images/twitter.svg
  public/stylesheets/style.css
  public/stylesheets/style.css.map
  routes/auth.js
  sass/stylesheets/style.scss
  views/index.hbs
  views/layout.hbs
Labels: Task

#186 Add css profile#178
  sass/stylesheets/style.scss
  views/events/events.hbs
  views/users/profile.hbs
Labels: css

#212 Visible only my pets#191
  package-lock.json
  routes/pets.js
  views/pets/addPet.hbs
Labels: improvement

#225 Change user to owner#222
  public/images/default-pet.png
  routes/pets.js
  views/pets/addPet.hbs
  views/pets/editPet.hbs
Labels: improvement

#233 Add backto profile button#208
  package-lock.json
  views/pets/addPet.hbs
  views/pets/editPet.hbs
  views/pets/petDetails.hbs
  views/users/profile.hbs
  views/users/update.hbs
Labels: css

#252 Add normalize#250
  sass/stylesheets/_normalize.scss
  sass/stylesheets/style.scss
Labels: css
